"use client";
import Feedback from "@/components/Feedback";
import Calendar from "@/components/Feedback";
import CategoryCard from "@/components/CategoryCard/CategoryCard";
import React from "react";

const items = [
  {
    title: "Modules",
    content: (
      <CategoryCard 
      title="Operating System" 
      items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: true,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 2,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/storage/fe121d443b662e6a8a224ff/2017/02/index.html",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/storage/fe121d443b662e6a8a224ff/2017/10/file_example_PNG_500kB.png",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/storage/fe121d443b662e6a8a224ff/2017/11/file_example_MP3_700KB.mp3",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/wp-content/storage/2018/04/file_example_AVI_480_750kB.avi",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/wp-content/storage/2017/02/file-sample_100kB.doc",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/wp-content/storage/2017/08/file_example_PPT_250kB.ppt",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/wp-content/storage/2017/02/file_example_XLS_10.xls",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://file-examples.com/wp-content/storage/2017/02/zip_2MB.zip",
            },

          ],
          solved: false,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 0,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard>
    ),
  },
  {
    title: "Students",
    content: (
      <CategoryCard title="Group 3" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 0,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: [],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard>
    ),
  },
  {
    title: "Adminitration",
    content: (
      <CategoryCard title="Admin" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard>
    ),
  },
  {
    title: "Logistics",
    content: (
      <CategoryCard title="Amphiteater" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard>
    ),
  },
  {
    title: "Clubs",
    content: (
      <><><CategoryCard title="GDSC ENSIA" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard><CategoryCard title="GDSC ENSIA" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard></><CategoryCard title="GDSC ENSIA" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard><CategoryCard title="GDSC ENSIA" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard><CategoryCard title="GDSC ENSIA" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard></>
    ),
  },
  {
    title: "Residancy",
    content: (
      <CategoryCard title="Mahelma 3" items={[
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Update user profile page UI",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        {
          title: "Add discount code to checkout page",
          avatarSrc: "https://i.pravatar.cc/100",
          username: "Username",
          date: "2019-09-14",
          time: "12:12",
          category: ["Tag1", "Tag2", "Tag3", "Tag4"],
          cluster: "Problem",
          archive: false,
          follow: false,
          likes: 214,
          comments: 5,
          myVote: true,
          priority: 1,
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. ",
          attachments: [
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },
            {
              title: "Displayed text here", 
              date: "2019-09-14",
              time: "12:12",
              username: "Username",
              description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
              url: "https://i.pravatar.cc/100",
            },

          ],
          solved: true,
        },
        // Add more items as needed
      ]}></CategoryCard>
    ),
  },
];

const FeedbackBoard: React.FC = () => {
  return (
    <>
      <Feedback items={items} />
    </>
  );
};

export default FeedbackBoard;
